---
  - name: Install DVWA
    hosts: webservers
    become: true
    tasks:

    - name: Install docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install docker
      pip:
        name: docker
        state: present

    - name: Install DVWA container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        published_ports: 80:80 
        restart_policy: always

    - name: check Docker is running
      ansible.builtin.systemd:
        state: started
        name: docker
   
