---
- name: installing and launching filebeat
  hosts: webservers
  become: yes
  tasks:

  - name: download filebeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

  - name: download metric
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: install filebeat deb
    command: dpkg -i /home/azadmin/filebeat-7.4.0-amd64.deb

  - name: install metric
    command: dpkg -i /home/azadmin/metricbeat-7.4.0-amd64.deb

  - name: copy in filebeat config
    copy:
      src: /etc/ansible/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: copy in metrics config
    copy: 
      src: /etc/ansible/metric-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: enable and config system module
    command: filebeat modules enable system

  - name: setup filebeat
    command: filebeat setup

  - name: start filebeat
    command: service filebeat start

  - name: enable on boot
    systemd:
      name: filebeat
      enabled: yes
